# Generated by Django 4.2.11 on 2024-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trojanlist',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='木马Hash'),
        ),
    ]
