# Generated by Django 4.2.11 on 2024-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0002_alter_trojanlist_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trojanlist',
            name='encode_key',
            field=models.CharField(default=0, max_length=64, verbose_name='encode_key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trojanlist',
            name='chosen_plan',
            field=models.CharField(max_length=20, verbose_name='chosen_plan'),
        ),
        migrations.AlterField(
            model_name='trojanlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creat_at'),
        ),
        migrations.AlterField(
            model_name='trojanlist',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='file_hash'),
        ),
        migrations.AlterField(
            model_name='trojanlist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='trojanlist',
            name='shellcode_remote',
            field=models.BooleanField(default=False, verbose_name='shellcode _remote'),
        ),
    ]
