# Generated by Django 4.2.11 on 2024-04-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trojan', '0003_trojanlist_encode_key_alter_trojanlist_chosen_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trojanlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trojan_created_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
