# Generated by Django 4.2.11 on 2024-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0004_trojanlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trojanlist',
            name='shellcode_file_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='shellcode_file_id'),
        ),
    ]
