# Generated by Django 4.2.11 on 2024-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0007_remove_trojanlist_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trojanlist',
            name='shellcode_path',
        ),
        migrations.AddField(
            model_name='trojanlist',
            name='shellcode_file_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='shellcode_file_name'),
        ),
    ]
