# Generated by Django 4.2.11 on 2024-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0009_trojanlist_icon_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trojanlist',
            name='icon_file_name',
        ),
        migrations.RemoveField(
            model_name='trojanlist',
            name='signature_file_name',
        ),
        migrations.AddField(
            model_name='trojanlist',
            name='icon_file',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='icon_file'),
        ),
        migrations.AddField(
            model_name='trojanlist',
            name='signature_file',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='signature_file'),
        ),
    ]
