# Generated by Django 4.2.11 on 2024-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0011_alter_trojanlist_icon_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trojanlist',
            name='shellcode_remote_addr',
            field=models.CharField(max_length=256, null=True, verbose_name='shellcode_remote_addr'),
        ),
    ]
