# Generated by Django 4.2.11 on 2024-04-08 12:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=user.models.user_directory_path),
        ),
    ]
