# Generated by Django 4.2.11 on 2024-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='hash',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
