# Generated by Django 4.2.11 on 2024-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_uploadedfile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
