# Generated by Django 4.2.11 on 2024-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_uploadedfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
