# Generated by Django 4.2.11 on 2024-05-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shellcode_ip_addr',
            field=models.CharField(max_length=255, null=True, verbose_name='shellcode_ip_addr'),
        ),
    ]
